import React, { useCallback, useEffect, useRef, useState } from "react";
import { View, StyleSheet, FlatList, TextInput, Pressable, KeyboardAvoidingView, Platform, ActivityIndicator } from "react-native";
import { useLocalSearchParams } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import dayjs from "dayjs";
import { ScreenHeader } from "../../src/components/ScreenHeader";
import { Txt, Loading, ErrorState } from "../../src/components/ui";
import { api, apiError } from "../../src/lib/api";
import { getSocket } from "../../src/lib/socket";
import { colors, spacing, font, radii } from "../../src/theme";

export default function SupportChat() {
  const { id } = useLocalSearchParams(); const listRef = useRef(null);
  const [ticket,setTicket]=useState(null); const [messages,setMessages]=useState([]); const [text,setText]=useState(""); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [error,setError]=useState("");
  const load=useCallback(async()=>{setError("");try{const d=(await api.get(`/support/${id}`)).data;setTicket(d.ticket);setMessages(d.messages||[]);}catch(e){setError(apiError(e,"Couldn't open this conversation."));}finally{setLoading(false);}},[id]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{const s=getSocket();if(!s)return;const message=(p)=>{if(String(p.ticketId)!==String(id))return;setMessages((old)=>old.some((m)=>m._id===p.message._id)?old:[...old,p.message]);};const status=(p)=>{if(String(p.ticketId)===String(id))setTicket((t)=>t?{...t,status:p.status}:t);};s.on("support:message:new",message);s.on("support:ticket:status",status);return()=>{s.off("support:message:new",message);s.off("support:ticket:status",status);};},[id]);
  const send=async()=>{const value=text.trim();if(!value||sending)return;setSending(true);setText("");try{const d=(await api.post(`/support/${id}/message`,{text:value})).data;setMessages((old)=>old.some((m)=>m._id===d.message._id)?old:[...old,d.message]);setTimeout(()=>listRef.current?.scrollToEnd({animated:true}),50);}catch(e){setText(value);setError(apiError(e,"Couldn't send message."));}finally{setSending(false);}};
  if(loading)return <View style={styles.root}><ScreenHeader title="Support chat"/><Loading label="Opening conversation…"/></View>;
  if(error&&!ticket)return <View style={styles.root}><ScreenHeader title="Support chat"/><ErrorState title="Couldn't open chat" subtitle={error} onRetry={load}/></View>;
  const closed=["resolved","closed"].includes(ticket?.status);
  return <KeyboardAvoidingView style={styles.root} behavior={Platform.OS==="ios"?"padding":"height"} keyboardVerticalOffset={0}><ScreenHeader title={ticket?.ticketNumber||"Support chat"}/><View style={styles.context}><View style={{flex:1}}><Txt weight={font.weight.semibold}>{ticket?.categoryLabel}</Txt><Txt faint size={font.size.xs} style={{marginTop:2}}>{closed?"Conversation closed":"Usually replies within 24 hours"}</Txt></View><View style={[styles.status,{backgroundColor:closed?colors.surfaceSunken:colors.successSoft}]}><Txt size={font.size.xs} weight={font.weight.semibold} color={closed?colors.textMuted:colors.success}>{closed?"Closed":"Active"}</Txt></View></View><FlatList ref={listRef} keyboardShouldPersistTaps="handled" keyboardDismissMode="interactive" data={messages} keyExtractor={(m)=>m._id} contentContainerStyle={styles.messages} onContentSizeChange={()=>listRef.current?.scrollToEnd({animated:false})} renderItem={({item,index})=><MessageBubble message={item} showLabel={index===0||messages[index-1].senderRole!==item.senderRole}/>} ListFooterComponent={error?<Txt color={colors.danger} center size={font.size.sm}>{error}</Txt>:null}/>{closed?<View style={styles.closed}><Ionicons name="checkmark-circle-outline" size={18} color={colors.textMuted}/><Txt muted size={font.size.sm}>This conversation is closed. Create a new request if you still need help.</Txt></View>:<View style={styles.composer}><TextInput value={text} onChangeText={(v)=>{setText(v.slice(0,2000));setError("");}} placeholder="Message support…" placeholderTextColor={colors.textFaint} multiline style={styles.input}/><Pressable onPress={send} disabled={!text.trim()||sending} style={[styles.send,(!text.trim()||sending)&&{opacity:.4}]}>{sending?<ActivityIndicator size="small" color={colors.textOnInk}/>:<Ionicons name="send" size={18} color={colors.textOnInk}/>}</Pressable></View>}</KeyboardAvoidingView>;
}
function MessageBubble({message,showLabel}){const mine=message.senderRole!=="admin";return <View style={[styles.bubbleWrap,mine?{alignItems:"flex-end"}:{alignItems:"flex-start"}]}>{!mine&&showLabel?<Txt faint size={font.size.xs} style={{marginBottom:4}}>EliteCrew Support</Txt>:null}<View style={[styles.bubble,mine?styles.mine:styles.theirs]}><Txt color={mine?colors.textOnInk:colors.text} style={{lineHeight:20}}>{message.text}</Txt></View><Txt faint size={10} style={{marginTop:3}}>{dayjs(message.createdAt).format("h:mm A")}</Txt></View>}

const styles=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},context:{flexDirection:"row",alignItems:"center",paddingHorizontal:spacing.xl,paddingVertical:spacing.md,borderBottomWidth:1,borderBottomColor:colors.border},status:{paddingHorizontal:10,paddingVertical:5,borderRadius:radii.pill},messages:{padding:spacing.xl,paddingBottom:spacing.xxl},bubbleWrap:{marginBottom:spacing.lg},bubble:{maxWidth:"82%",paddingHorizontal:spacing.md,paddingVertical:10,borderRadius:radii.lg},mine:{backgroundColor:colors.ink,borderBottomRightRadius:3},theirs:{backgroundColor:colors.surfaceAlt,borderWidth:1,borderColor:colors.border,borderBottomLeftRadius:3},composer:{flexDirection:"row",alignItems:"flex-end",gap:spacing.sm,padding:spacing.md,borderTopWidth:1,borderTopColor:colors.border,backgroundColor:colors.surface},input:{flex:1,maxHeight:110,minHeight:44,borderWidth:1,borderColor:colors.borderStrong,borderRadius:22,paddingHorizontal:spacing.lg,paddingTop:11,paddingBottom:10,fontSize:font.size.base,color:colors.text},send:{width:44,height:44,borderRadius:22,backgroundColor:colors.ink,alignItems:"center",justifyContent:"center"},closed:{flexDirection:"row",alignItems:"center",gap:spacing.sm,padding:spacing.lg,backgroundColor:colors.surfaceAlt,borderTopWidth:1,borderTopColor:colors.border}});


